"""Catalogue des flux RSS (presse cinéma / séries / anime-manga / streaming)."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Source:
    key: str
    name: str
    url: str
    category: str
    country: str
    color: str
    site: str


CATEGORIES: dict[str, str] = {
    "cinema": "Cinéma",
    "series": "Séries",
    "anime": "Anime & Manga",
    "streaming": "Streaming",
    "industrie": "Industrie",
}

SOURCES: list[Source] = [
    # --- Cinéma ---
    Source(
        "allocine",
        "AlloCiné",
        "https://www.allocine.fr/rss/news.xml",
        "cinema",
        "FR",
        "#FECC00",
        "https://www.allocine.fr",
    ),
    Source(
        "premiere",
        "Première",
        "https://www.premiere.fr/rss.xml",
        "cinema",
        "FR",
        "#E4002B",
        "https://www.premiere.fr",
    ),
    Source(
        "ecranlarge",
        "Écran Large",
        "https://www.ecranlarge.com/rss",
        "cinema",
        "FR",
        "#F5A623",
        "https://www.ecranlarge.com",
    ),
    Source(
        "lemonde-cinema",
        "Le Monde Cinéma",
        "https://www.lemonde.fr/cinema/rss_full.xml",
        "cinema",
        "FR",
        "#1B1B1B",
        "https://www.lemonde.fr/cinema/",
    ),
    Source(
        "lefigaro-cinema",
        "Le Figaro Cinéma",
        "https://www.lefigaro.fr/rss/figaro_cinema.xml",
        "cinema",
        "FR",
        "#1B3F8F",
        "https://www.lefigaro.fr/cinema",
    ),
    Source(
        "franceinfo-cinema",
        "franceinfo Cinéma",
        "https://www.francetvinfo.fr/culture/cinema.rss",
        "cinema",
        "FR",
        "#0A0A2A",
        "https://www.franceinfo.fr/culture/cinema/",
    ),
    Source(
        "telerama-cinema",
        "Télérama Cinéma",
        "https://www.telerama.fr/rss/cinema.xml",
        "cinema",
        "FR",
        "#E2001A",
        "https://www.telerama.fr/cinema",
    ),
    Source(
        "variety-film",
        "Variety Film",
        "https://variety.com/v/film/feed/",
        "cinema",
        "US",
        "#D40000",
        "https://variety.com",
    ),
    Source(
        "indiewire",
        "IndieWire",
        "https://www.indiewire.com/feed/",
        "cinema",
        "US",
        "#FF3B30",
        "https://www.indiewire.com",
    ),
    Source(
        "slashfilm",
        "/Film",
        "https://www.slashfilm.com/feed/",
        "cinema",
        "US",
        "#000000",
        "https://www.slashfilm.com",
    ),
    Source(
        "collider",
        "Collider",
        "https://collider.com/feed/",
        "cinema",
        "US",
        "#E11D2E",
        "https://collider.com",
    ),
    Source(
        "screenrant",
        "Screen Rant",
        "https://screenrant.com/feed/",
        "cinema",
        "US",
        "#FF6A00",
        "https://screenrant.com",
    ),
    # --- Séries ---
    Source(
        "allocine-series",
        "AlloCiné Séries",
        "https://www.allocine.fr/rss/news-series.xml",
        "series",
        "FR",
        "#FECC00",
        "https://www.allocine.fr/series/",
    ),
    Source(
        "telerama-series",
        "Télérama Séries",
        "https://www.telerama.fr/rss/series-tv.xml",
        "series",
        "FR",
        "#E2001A",
        "https://www.telerama.fr/series-tv",
    ),
    Source(
        "variety-tv",
        "Variety TV",
        "https://variety.com/v/tv/feed/",
        "series",
        "US",
        "#D40000",
        "https://variety.com/v/tv/",
    ),
    Source(
        "tvline",
        "TVLine",
        "https://tvline.com/feed/",
        "series",
        "US",
        "#0077C8",
        "https://tvline.com",
    ),
    Source(
        "deadline",
        "Deadline",
        "https://deadline.com/feed/",
        "series",
        "US",
        "#C8102E",
        "https://deadline.com",
    ),
    Source(
        "thr-tv",
        "Hollywood Reporter TV",
        "https://www.hollywoodreporter.com/c/tv/feed/",
        "series",
        "US",
        "#000000",
        "https://www.hollywoodreporter.com/c/tv/",
    ),
    # --- Anime & Manga ---
    Source(
        "ann",
        "Anime News Network",
        "https://www.animenewsnetwork.com/all/rss.xml",
        "anime",
        "US",
        "#2E6DB4",
        "https://www.animenewsnetwork.com",
    ),
    Source(
        "manga-news",
        "Manga-news",
        "https://www.manga-news.com/index.php/feed/news",
        "anime",
        "FR",
        "#E4002B",
        "https://www.manga-news.com",
    ),
    Source(
        "animeland",
        "AnimeLand",
        "https://animeland.fr/feed/",
        "anime",
        "FR",
        "#F26522",
        "https://animeland.fr",
    ),
    Source(
        "journaldujapon",
        "Journal du Japon",
        "https://www.journaldujapon.com/feed/",
        "anime",
        "FR",
        "#BC002D",
        "https://www.journaldujapon.com",
    ),
    Source(
        "crunchyroll-news",
        "Crunchyroll News FR",
        "https://cr-news-api-service.prd.crunchyrollsvc.com/v1/fr-FR/rss",
        "anime",
        "FR",
        "#F47521",
        "https://www.crunchyroll.com/news",
    ),
    Source(
        "adala",
        "Adala News",
        "https://adala-news.fr/feed/",
        "anime",
        "FR",
        "#7B2CBF",
        "https://adala-news.fr",
    ),
    # --- Streaming ---
    Source(
        "whats-on-netflix",
        "What's on Netflix",
        "https://www.whats-on-netflix.com/feed/",
        "streaming",
        "US",
        "#E50914",
        "https://www.whats-on-netflix.com",
    ),
    Source(
        "numerama-pop",
        "Numerama Pop culture",
        "https://www.numerama.com/pop-culture/feed/",
        "streaming",
        "FR",
        "#00A3E0",
        "https://www.numerama.com/pop-culture/",
    ),
    Source(
        "journaldugeek",
        "Journal du Geek",
        "https://www.journaldugeek.com/feed/",
        "streaming",
        "FR",
        "#1E90FF",
        "https://www.journaldugeek.com",
    ),
    Source(
        "thr-movies",
        "Hollywood Reporter Movies",
        "https://www.hollywoodreporter.com/c/movies/feed/",
        "streaming",
        "US",
        "#000000",
        "https://www.hollywoodreporter.com/c/movies/",
    ),
    # --- Industrie / box-office ---
    Source(
        "variety-boxoffice",
        "Variety Box Office",
        "https://variety.com/t/box-office/feed/",
        "industrie",
        "US",
        "#D40000",
        "https://variety.com/t/box-office/",
    ),
    Source(
        "leparisien-cinema",
        "Le Parisien Cinéma",
        "https://www.leparisien.fr/culture-loisirs/cinema/rss.xml",
        "industrie",
        "FR",
        "#1F4FA3",
        "https://www.leparisien.fr/culture-loisirs/cinema/",
    ),
    Source(
        "variety-biz",
        "Variety Biz",
        "https://variety.com/v/biz/feed/",
        "industrie",
        "US",
        "#D40000",
        "https://variety.com/v/biz/",
    ),
]

SOURCES_BY_KEY = {s.key: s for s in SOURCES}
